# QCArchive Demo
## Day 2

In [1]:
import qcportal as ptl
client = ptl.FractalClient()

In [3]:
client

FractalClient(server_name='The MolSSI QCArchive Server', address='https://api.qcarchive.molssi.org:443/', username='None')

In [4]:
butane = client.query_molecules(id=['61139', '70659'])

In [5]:
butane

[<Molecule(name='C4H10' formula='C4H10' hash='3bbc6db')>,
 <Molecule(name='C4H10' formula='C4H10' hash='bb665a3')>]

In [43]:
butane[0].show()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [7]:
butane[0].symbols

['C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H']

In [14]:
butane_geometries = [butane[0].geometry.copy(), butane[1].geometry.copy()]

In [18]:
import numpy as np

def calculate_distance(rA, rB):
    """Calculate the distance between points A and B"""
    dist_vec = (rA - rB)
    distance = np.linalg.norm(dist_vec)
    return distance

In [19]:
def build_bond_list(coordinates, max_bond=1.55, min_bond=0):
    num_atoms = len(coordinates)
    
    bonds = {}
    
    for atom1 in range(num_atoms):
        for atom2 in range(atom1, num_atoms):
            distance = calculate_distance(coordinates[atom1], coordinates[atom2])
            
            if distance > min_bond and distance < max_bond:
                bonds[(atom1, atom2)] = distance
    
    return bonds

In [35]:
bond_list = build_bond_list(butane_geometries[0], max_bond = 2.93)

In [36]:
bond_list

{(0, 2): 2.873020656801253,
 (0, 4): 2.068839651551603,
 (0, 5): 2.068484041315794,
 (0, 6): 2.068821759435787,
 (1, 3): 2.873059651780396,
 (1, 7): 2.068247482474781,
 (1, 8): 2.0685780442929644,
 (1, 9): 2.0687346633381822,
 (2, 3): 2.8862132661474598,
 (2, 10): 2.0715801221019885,
 (2, 11): 2.0716218178677623,
 (3, 12): 2.0713472807014583,
 (3, 13): 2.071754810836534}

In [38]:
butane[0].connectivity

[(0, 2, 1.0),
 (0, 4, 1.0),
 (0, 5, 1.0),
 (0, 6, 1.0),
 (1, 3, 1.0),
 (1, 7, 1.0),
 (1, 8, 1.0),
 (1, 9, 1.0),
 (2, 3, 1.0),
 (2, 10, 1.0),
 (2, 11, 1.0),
 (3, 12, 1.0),
 (3, 13, 1.0)]

In [23]:
butane[0].geometry

array([[ 0.60309252, -2.0666753 , -2.95631542],
       [-0.54975128,  2.07257294,  2.96267825],
       [ 0.17543623, -1.41965569, -0.1899598 ],
       [-0.17535536,  1.41986451,  0.18990506],
       [-0.98243014, -1.42706018, -4.12126516],
       [ 2.32107194, -1.14665691, -3.64966894],
       [ 0.81868895, -4.10783439, -3.21556669],
       [ 1.07104045,  1.43010767,  4.07529687],
       [-2.24715359,  1.16149057,  3.71618302],
       [-0.73832413,  4.11600143,  3.22440978],
       [ 1.79270627, -2.08396319,  0.92115557],
       [-1.4961426 , -2.4339562 ,  0.49460988],
       [-1.81551707,  2.07754179, -0.89074739],
       [ 1.48034939,  2.43606453, -0.52991943]])

In [24]:
print(len(butane[0].geometry))
print(len(butane[0].symbols))

14
14


In [25]:
atom1 = butane_geometries[0][0]
print(atom1)

[ 0.60309252 -2.0666753  -2.95631542]


In [27]:
atom2 = butane_geometries[0][1]
print(atom2)

[-0.54975128  2.07257294  2.96267825]


In [29]:
measured_distance = calculate_distance(atom1,atom2)
print(measured_distance)

7.314158248564329


In [30]:
butane[0].measure([0,1])

7.31415824856433

In [32]:
# use calculate_distance function to measure between atoms 3 and 10 in the second butane molecule
butane[1].measure([2,9])

6.71634950813261

In [33]:
bond_list2 = build_bond_list(butane_geometries[1])
atom3 = butane_geometries[1][2]
atom10 = butane_geometries[1][9]
measured_distance2 = calculate_distance(atom3,atom10)
print(measured_distance2)

6.71634950813261


In [34]:
qcarchive_distance = butane[1].measure([2,9])
print(qcarchive_distance)

6.71634950813261


In [39]:
import qcelemental

angstrom_to_bohr = qcelemental.constants.conversion_factor("angstrom","bohr")
print(angstrom_to_bohr)

1.8897261254578281


In [40]:
max_length = 1.55*angstrom_to_bohr

In [47]:
#use qcportal to acess a geometry optimization calculation
#use query_procedures
# id = 2658710

geometry_opt_calc=client.query_procedures(id=['2658710'])
geometry_opt_calc

[<OptimizationRecord(id='2658710' status='COMPLETE')>]

In [48]:
opt = geometry_opt_calc[0]

In [52]:
initial = opt.get_initial_molecule()
initial.show()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [56]:
final = opt.get_final_molecule()
final.show()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [51]:
initial.connectivity

In [54]:
#max bond length is 2.93

initial_coordinates = initial.geometry.copy()
final_coordinates = final.geometry.copy()

initial_bonds =  build_bond_list(initial_coordinates, max_bond = 2.93)
final_bonds = build_bond_list(final_coordinates, max_bond = 2.93)

In [55]:
initial_bonds

{(0, 1): 2.6853008199999997,
 (0, 5): 2.685300947458371,
 (0, 54): 2.0494834766860643,
 (1, 6): 2.6853009524690883,
 (1, 55): 2.0494834766860643,
 (2, 3): 2.6853008199999997,
 (2, 9): 2.685300947458371,
 (2, 56): 2.0494834766860643,
 (3, 10): 2.6853009524690883,
 (3, 57): 2.0494834766860643,
 (4, 5): 2.685300829999999,
 (4, 13): 2.685300829993184,
 (4, 58): 2.0494834770587396,
 (5, 14): 2.6852998829666923,
 (6, 7): 2.68530082,
 (6, 15): 2.6852998879774117,
 (7, 16): 2.6852998879774117,
 (7, 59): 2.0494834871062877,
 (8, 9): 2.685300829999999,
 (8, 19): 2.685300829993184,
 (8, 60): 2.0494834770587396,
 (9, 20): 2.6852998829666923,
 (10, 11): 2.68530082,
 (10, 21): 2.6852998879774117,
 (11, 22): 2.6852998879774117,
 (11, 61): 2.0494834871062877,
 (12, 13): 2.685300829999999,
 (12, 24): 2.6852998829666923,
 (12, 62): 2.049483475383679,
 (13, 25): 2.685300829993184,
 (14, 15): 2.6853008199999997,
 (14, 26): 2.6852998829666923,
 (15, 27): 2.6852998879774117,
 (16, 17): 2.68530082,
 (16, 28)

In [57]:
#compare the two dictionaries initial_bonds and final_bonds to find the change in bond length for each bond
for k in initial_bonds:
    diff = final_bonds[k] - initial_bonds[k]
    print(k, diff)

(0, 1) -0.12125783998247419
(0, 5) 0.03652933845980799
(0, 54) 0.0013072821258468537
(1, 6) 0.0365286356592871
(1, 55) 0.0013065023782292684
(2, 3) -0.12125319998628425
(2, 9) 0.036530668675503364
(2, 56) 0.0013062416111879749
(3, 10) 0.0365312833547744
(3, 57) 0.0013068556466429015
(4, 5) -0.04903193300734543
(4, 13) -0.0490720625963279
(4, 58) 0.003137346014596698
(5, 14) 0.010798420718752144
(6, 7) -0.04903028628599815
(6, 15) 0.01079988956621758
(7, 16) -0.04907121615054244
(7, 59) 0.0031362976027144995
(8, 9) -0.049024471064973874
(8, 19) -0.04906907865232091
(8, 60) 0.003135298936773445
(9, 20) 0.010799063343710724
(10, 11) -0.04902644295843839
(10, 21) 0.010798380165098376
(11, 22) -0.0490686525226276
(11, 61) 0.003135746517670235
(12, 13) 0.03673448192571094
(12, 24) -0.12113026442271035
(12, 62) 0.001361072035932498
(13, 25) 0.010758433401821588
(14, 15) 0.005330890020097456
(14, 26) -0.0026306061759662214
(15, 27) -0.002632849027812245
(16, 17) 0.03673683749261869
(16, 28) 0.